### ISSUE TITLE
Em service

### ISSUE THREAD

**Issue by JackWh0** [andersonmag/E-nology-POWERFULL#36]
Sequênciador
- Buscar tarefas com palavras do conteúdo x;

Lista de tarefas
- Quantas questões
- Qual ordem

**Comment by priscyllaifal** [comment]
class SequenciadorService {
           public List<Tarefa> buscarTarefa(Conteudo conteudo){
                       // usar o repositorio para buscar todas as tarefas do banco
                       // pegar todas as palavras do conteúdo e criar uma lista
                      // filtrar na lista de tarefas apenas as relacionadas as palavras da lista de palavras
                     //retorna a lista de tarefas filtrada
          }
}
